# noctalia-greeter sync.toml (UI + Sync; not managed by Nix)
# [session] last, [session.power] suspend/reboot/shutdown, [[session.actions]] action/command/label/glyph
# [appearance] scheme, theme_mode, corner_radius_scale, font_family
# [appearance.palette] full color role table, [appearance.wallpaper]/[appearance.wallpapers.<connector>]
# [output] layout/transforms

[appearance]
# Workaround to make corners squared: https://github.com/noctalia-dev/noctalia-greeter/issues/89
corner_radius_scale = 0.10000000149011612
font_family = "Maple Mono"
scheme = "Synced"
theme_mode = "dark"

    [appearance.palette]
    error = "#FF8080"
    hover = "#FBADFF"
    on_error = "#000000"
    on_hover = "#000000"
    on_primary = "#000000"
    on_secondary = "#000000"
    on_surface = "#FFFFFF"
    on_surface_variant = "#A0A0A0"
    on_tertiary = "#000000"
    outline = "#383838"
    primary = "#FFC799"
    secondary = "#99FFE4"
    shadow = "#000000"
    surface = "#0C0C0C"
    surface_variant = "#1C1C1C"
    tertiary = "#FBADFF"

    [appearance.wallpaper]
    fill_mode = "crop"
    path = "/var/lib/noctalia-greeter/wallpaper.jpg"

    [appearance.wallpapers.DP-1]
    fill_mode = "crop"
    path = "/var/lib/noctalia-greeter/wallpaper-DP-1.jpg"

    [appearance.wallpapers.eDP-1]
    fill_mode = "crop"
    path = "/var/lib/noctalia-greeter/wallpaper-eDP-1.jpg"

[output]
layout = "eDP-1:0,0; DP-1:1707,0"
transforms = "eDP-1:normal"

[session]
last = "Niri"