color0 #101010
color1 #f7a2a4
color2 #bfd69a
color3 #eed4a0
color4 #98d1c9
color5 #e0aac4
color6 #9dd6ab
color7 #e9e0cd
color8 #9aa79e
color9 #f7a2a4
color10 #bfd69a
color11 #eed4a0
color12 #98d1c9
color13 #e0aac4
color14 #9dd6ab
color15 #e9e0cd

cursor #e9e0cd
cursor_text_color #101010
background #0c0c0c
foreground #e9e0cd
selection_foreground #e9e0cd
selection_background #4c3743
active_border_color #bfd69a
inactive_border_color #374145
url_color #98d1c9

active_tab_foreground #e9e0cd
active_tab_background #3c4841
inactive_tab_foreground #9aa79e
inactive_tab_background #101010
cursor_trail_color #374145