[audio]
enable_overdrive = true

[backdrop]
enabled = true
tint_intensity = 0.0

[bar.default]
capsule_radius = 20
center = [ "clock" ]
end = [ "audio_visualizer", "tray", "battery", "network", "volume", "brightness", "notifications" ]
margin_ends = 0
padding = 20
position = "left"
radius = 0
radius_bottom_right = 12
radius_top_right = 12
scale = 0.85
shadow = false
start = [ "overview", "workspaces", "group:g1" ]
thickness = 30
widget_spacing = 16

    [bar.default.dead_zone.actions]
    left = "exec noctalia msg notification-clear-active"
    middle = "volume-mute"
    scroll_down = "volume-down 2"
    scroll_up = "volume-up 2"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface"
    id = "g1"
    members = [ "cpu", "temp", "ram" ]
    opacity = 1.0
    padding = 6.0
    radius = 20.0
    widget_spacing = 8

[battery]
warning_threshold = 25

    [battery.device."/org/freedesktop/UPower/devices/keyboard_dev_CA_A1_51_60_60_75"]
    warning_threshold = 25

[brightness]
sync_all_monitors = false

[control_center]
sidebar_section = "none"

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
active_monitor_only = true
auto_hide = true
background_opacity = 1
enabled = false
icon_size = 24
launcher_icon = "background"
launcher_position = "start"
radius = 0
reserve_space = false
shadow = false

[hot_corners]
delay_ms = 500
enabled = false

    [hot_corners.top_left]
    action = "none"
    command = "niri msg action toggle-overview"

[keybinds]
down = [ "Down", "Ctrl+n" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+p" ]

[location]
address = "Hanoi"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 854.0
    cy = 948.0
    enabled = false
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 854.0
    cy = 948.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = false
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

[nightlight]
enabled = true
force = true
temperature_day = 4800
temperature_night = 4700

[notification]
background_opacity = 1.0
border = false

[osd]
background_opacity = 1.0
border = false
position = "top_right"

    [osd.kinds]
    keyboard_layout = false

[plugin_settings."felipeartur/ai-usagebar"]
panel_open_near_click = true
refresh_minutes = 1

[plugin_settings."noctalia/translator"]
target_lang = "vi"

[plugins]
enabled = [ "noctalia/translator", "salemsayed/codexbar-meter" ]

[shell]
app_icon_color = "primary"
button_borders = false
corner_radius_scale = 1.0
font_family = "Maple Mono"
polkit_agent = true
screen_time_enabled = true

    [shell.animation]
    speed = 2.0

    [shell.greeter_sync]
    auto_sync = false

    [shell.launcher]
    categories = false

        [shell.launcher.providers.emoji]
        prefix = ""

        [shell.launcher.providers.session]
        global = true

    [shell.panel]
    clipboard_placement = "floating"
    open_near_click_control_center = true
    shadow = false

    [shell.screen_corners]
    enabled = true
    size = 28

    [shell.screenshot]
    remember_last_region = true
    save_to_file = false

    [shell.session]
    show_shortcuts = false

    [shell.shadow]
    alpha = 0.0

[theme]
builtin = "Ayu"
community_palette = "Vesper"
custom_palette = "custom"
source = "custom"
wallpaper_scheme = "m3-content"

[wallpaper]
edge_smoothness = 0.0
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/zen/Pictures/Wallpapers/alpine.jpg"

    [wallpaper.last]
    path = "/home/zen/Pictures/Wallpapers/alpine.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/zen/Pictures/Wallpapers/alpine.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/zen/Pictures/Wallpapers/alpine.jpg"

[weather]
enabled = false

[widget.Overview]
glyph = "navigation-filled"
tooltip = "Overview"
type = "custom_button"

    [widget.Overview.actions]
    left = "exec niri msg action toggle-overview"

[widget.audio_visualizer]
centered = true
mirrored = false

    [widget.audio_visualizer.actions]
    left = "panel-toggle control-center media"

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.bar_2]
type = "salemsayed/codexbar-meter:bar"

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

    [widget.brightness.actions]
    scroll_down = "brightness-down 2%"
    scroll_up = "brightness-up 2%"

[widget.clock]
format = "{:%H %M %u %d %m %y}"
tooltip_format = "{:%H:%M %a, %b %m}"
vertical_format = "{:%H %M%n%u%n%d %m %y}"

[widget.control-center]
enabled = true
glyph = "navigation-filled"

[widget.cpu]
show_value = false

[widget.input_volume]
show_label = false

[widget.media]
hide_album_art = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false
vpn_status = "both"

[widget.overview]
glyph = "navigation-filled"
tooltip = "Overview"
type = "custom_button"

    [widget.overview.actions]
    left = "exec niri msg action toggle-overview"

[widget.ram]
show_value = false

[widget.sysmon]
show_value = false
stat = "gpu_usage"

[widget.temp]
show_value = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false

    [widget.volume.actions]
    scroll_down = "volume-down 2"
    scroll_up = "volume-up 2"

[widget.workspaces]
empty_color = "outline"
hide_when_empty = true
inactive_pill_size = 1.2
labels_only_when_occupied = true
occupied_color = "outline"
pill_scale = 0.85
show_labels = false
