[audio]
enable_overdrive = true

[bar.default]
start = [ "clock", "cpu", "temp", "ram", "media" ]
center = [ "workspaces" ]
end = [ "audio_visualizer", "tray", "notifications", "battery", "network", "volume", "input_volume", "brightness", "bar" ]
margin_ends = 0
padding = 12
radius = 0
capsule_radius = 0
scale = 0.85
shadow = false
thickness = 24
widget_spacing = 8

[bar.default.dead_zone.actions]
left = "exec noctalia msg notification-clear-active"
middle = "exec noctalia msg volume-mute"
scroll_down = "exec noctalia msg volume-down 2"
scroll_up = "exec noctalia msg volume-up 2"

[battery]
warning_threshold = 25

[brightness]
sync_all_monitors = true

[control_center]
sidebar_section = "none"

[desktop_widgets]
schema_version = 2
widget_order = []

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[desktop_widgets.widget]

[dock]
active_monitor_only = true
auto_hide = true
background_opacity = 1
enabled = true
icon_size = 24
launcher_icon = "background"
launcher_position = "start"
radius = 0
reserve_space = false
shadow = false

[keybinds]
down = [ "Down", "Ctrl+n" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+p" ]

[location]
address = "Hanoi"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@eDP-1" ]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
box_height = 201.0
box_width = 720.0
cx = 854.0
cy = 948.0
output = "DP-1"
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "compact"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_session_buttons = true

[nightlight]
enabled = true
force = true
temperature_day = 4800
temperature_night = 4700

[notification]
background_opacity = 1
border = false

[osd]
background_opacity = 1
border = false
position = "top_right"

[plugin_settings."noctalia/translator"]
target_lang = "vi"

[plugins]
enabled = [ "noctalia/translator", "noctalia/timer" ]

[shell]
app_icon_color = "primary"
button_borders = false
corner_radius_scale = 0.0
font_family = "Maple Mono"
polkit_agent = true
screen_time_enabled = true

[shell.animation]
speed = 2.0000000298023224

[shell.greeter_sync]
auto_sync = true

[shell.launcher]
categories = false

[shell.launcher.providers.emoji]
prefix = ""

[shell.launcher.providers.session]
global = true

[shell.panel]
clipboard_placement = "floating"
open_near_click_control_center = true
shadow = false

[shell.shadow]
alpha = 0.0

[theme]
builtin = "Kanagawa"
community_palette = "Vesper"
source = "community"

[theme.templates]
builtin_ids = [ "btop" ]

[wallpaper]
edge_smoothness = 0.0
transition = [ "disc" ]
transition_on_startup = true

[wallpaper.default]
path = "/home/zen/Pictures/Wallpapers/tori-gate.jpg"

[wallpaper.last]
path = "/home/zen/Pictures/Wallpapers/tori-gate.jpg"

[wallpaper.monitors.DP-1]
path = "/home/zen/Pictures/Wallpapers/tori-gate.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/zen/Pictures/Wallpapers/tori-gate.jpg"

[weather]
enabled = false

[widget.audio_visualizer]
centered = false
mirrored = false

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.brightness.actions]
scroll_down = "brightness-down 2%"

[widget.clock]
format = "{:%H:%M %a, %b %d}"

[widget.control-center]
enabled = true

[widget.cpu]
show_value = false

[widget.input_volume]
show_label = false

[widget.media]
hide_album_art = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false
vpn_status = "both"

[widget.ram]
show_value = false

[widget.sysmon]
show_value = false
stat = "gpu_usage"

[widget.temp]
show_value = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.workspaces]
empty_color = "on_primary"
hide_when_empty = true
labels_only_when_occupied = true
occupied_color = "on_primary"
