cursor_trail 1
window_padding_width 30
confirm_os_window_close 0

allow_remote_control yes
listen_on unix:/tmp/kitty.sock

map --allow-fallback=shifted,ascii ctrl+c copy_or_noop
map --allow-fallback=shifted,ascii ctrl+v paste_from_clipboard

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
