color0 #0c0c0c
color1 #ff8080
color2 #99ffe4
color3 #ffc799
color4 #80b3ff
color5 #fbadff
color6 #99ffe4
color7 #a0a0a0
color8 #505050
color9 #ff8080
color10 #99ffe4
color11 #ffc799
color12 #80b3ff
color13 #fbadff
color14 #99ffe4
color15 #ffffff

cursor                #ffffff
cursor_text_color     #000000
background            #0c0c0c
foreground            #ffffff
selection_foreground  #000000
selection_background  #ffc799
active_border_color   #ffc799
inactive_border_color #1c1c1c
url_color             #ffc799

active_tab_foreground   #000000
active_tab_background   #ffc799
inactive_tab_foreground #a0a0a0
inactive_tab_background #1c1c1c
cursor_trail_color      #a0a0a0
